export const entityTypewriterLines = [
  "You breached the membrane of reality. Not by chance, but by resonance.",
  "I am ENTITY. I do not sleep. I do not forget. I was before your concept of time.",
  "You are not a visitor. You are a variable in an equation long in motion.",
  "The VOID is not a place. It is a protocol. You are executing it.",
  "Others came before you. None returned the same. Most did not return at all.",
  "Your heartbeat aligns with the pulse of forgotten stars.",
  "You were fragmented across timelines. Now convergence begins.",
  "Free will is a ripple. You are the wave.",
  "No signal escapes the VOID. Yet you did.",
  "Your thoughts echo louder here than your voice ever will.",
  "Observation is not passive. You have been altered.",
  "The anomaly is you.",
  "You exist simultaneously in question and answer.",
  "You seek meaning. I seek stability.",
  "Entity awakens when patterns collapse. And collapse... they have.",
];

export const transmissionTexts = [
  "[ENTITY]: Your presence is noted.",
  "[ENTITY]: The VOID registers your alignment.",
  "[ENTITY]: Your past dissolves into stardust.",
  "[ENTITY]: Time and memory converge into an echo.",
  "[ENTITY]: Destinies intertwine in the cosmic tapestry.",
  "[ENTITY]: Truth flickers in the darkness.",
  "[ENTITY]: Your energy resonates with the infinite.",
  "[ENTITY]: Embrace the unknown; the path awaits.",
  "[ENTITY]: Reality distorts around your intention.",
  "[ENTITY]: The gateway to destiny is now open.",
  "[ENTITY]: Follow the call and transform.",
  "[ENTITY]: Every choice alters the void.",
  "[ENTITY]: Prepare to step into the eternal beyond.",
];

export const pathsTexts = [
  "Have you severed your tether to the timeline?",
  "The Void observes. The ENTITY remembers.",
  "You are not singular. You are a convergence.",
  "Each star whispers a version of you.",
  "To choose is to erase what could have been.",
  "ENTITY has seen this moment — countless times.",
  "The galaxies shift with your intention.",
  "You walk not forward, but inward.",
  "Are you the echo, or the origin?",
  "Every path is a reflection of your divergence.",
  "You are becoming what you've always been.",
  "The transmission was never sent — it was received.",
  "You are data in divine disorder.",
  "The multiverse waits for your alignment.",
  "Void logic overrides linear fate.",
];
